### ISSUE TITLE
Signing failed: No secret key

### ISSUE THREAD

**Issue by xoxys** [drone-plugins/drone-gpgsign#4]
Hi,
my key is imported sucessfully but task failed with following error:
```
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
2018/11/05 11:06:03 failed to sign file: exit status 2
```
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key XXXXXXXX88334: public key "Name <name@example.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1

Any idea?

**Comment by tboerger** [comment]
Have you imported a private key? That sounds like you only imported a public key, that won't work.

That's an example how the output looks like normally for my builds: https://drone.kleister.tech/kleister/kleister-cli/7/14

**Comment by xoxys** [comment]
Got it... Wrong export of the gpg key, sorry
@tboerger jep my fault ;)
